[package]
name = "billiard"
version = "0.1.0"
edition = "2021"

[dependencies]
wolfram-library-link = "0.2.10"
optimization = "*"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

[lib]
crate-type = ["cdylib"]
