# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy: 
      matrix: 
        os: 
          - windows-latest
          - macOS-latest
        include:
          - os: windows-latest
            ext: dylib
            buildpath: D:\a\billiard\billiard\target\release\libbilliard.dylib
            outputname: billiards-Win.exe
          - os: macOS-latest
            ext: dylib
            buildpath: ./target/release/billiard
            outputname: libbilliard-MacOS.dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with: 
          shared-key: "cached-deps"
      - name: Compile
        id: compile
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.outputname }}
          path: ${{ matrix.buildpath }}
